### ISSUE TITLE
No forms for enter username and password in Numix Theme.

### ISSUE THREAD

**Issue by ghost** [linuxmint/mint-mdm-themes#15]
I installed this package. But Bernard's themes are no forms to enter username and password. I attached screenshots. You can see how it looks. How to solve this problem? Thank you.

![sc1](https://cloud.githubusercontent.com/assets/10356808/5852273/d33a8e0a-a235-11e4-88b5-cf04901543e3.png)

![sc2](https://cloud.githubusercontent.com/assets/10356808/5852130/9db54b6e-a233-11e4-83a0-8010c9cc80d1.png)

**Comment by xenopeek** [comment]
The theme works fine on the login screen. Tested on Linux Mint 18.3 Cinnamon.
