### ISSUE TITLE
SpaceRace theme: alert message positioned incorrectly

### ISSUE THREAD

**Issue by ghost** [linuxmint/mint-mdm-themes#19]
When I write the wrong password in the login screen, the box of the alert message is positioned a little to the left. I tried to take a screenshot, but it doesn't work in the login screen, so I took a picture of the theme in the settings panel and drew a box where the real one is(kind of), so you can understand my problem better. Here's a link: http://postimg.org/image/vdfteav85/ (I drew the red line a little too high, ignore it's height)

**Comment by xenopeek** [comment]
Indeed alignment in the screenshot is a bit off but it doesn't prevent the theme from working. We'll continue to fix MDM bugs but beautifying MDM themes is out of scope.
