### ISSUE TITLE
Login Window themes missing Mint-Y-Dark and Mint-Y-Darker

### ISSUE THREAD

**Issue by ZupoLlask** [linuxmint/mint-mdm-themes#20]
If auto-logon is disabled, there is no proper Mint-Y-Dark or Mint-Y-Darker theme for Login Window.

**Comment by xenopeek** [comment]
This doesn't have enough information to go on. If the issue still happens, please test against the latest Linux Mint version, go through troubleshooting (see our [guide](http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/)) and create a new issue if the responsible component proves to be Login Window.
