### ISSUE TITLE
Supperposed Session/Launguage selection on html theme 

### ISSUE THREAD

**Issue by rogue-spectre** [linuxmint/mint-mdm-themes#22]
Hi,
    a little bug for html-theme spotted of Mint-X. If one click on Session or Language selection and click after on the other one without having set his selection, the two selection menus are visible whereas the first one should be hidden.

![superposed_lang_session](https://cloud.githubusercontent.com/assets/2879782/21566650/313c4500-cea5-11e6-951f-ca3227cd2c93.png)

it seems that the problem is related to popover function.

Nice week end

**Comment by rogue-spectre** [comment]
Solved it using popover('hide') modifying in index.html 


    // Context menus (bootstrap popover)
    $('#current_session_picture').popover({
        html : true,
        title: function() { return $("#sessions-title").html(); },
        content: function() { return $("#sessions-body").html(); }
    });

    $('#current_language_flag').popover({
        html : true,
        title: function() { return $("#languages-title").html(); },
        content: function() { return $("#languages-body").html(); }
    });


by


    // Context menus (bootstrap popover)
    $('#current_session_picture').popover({

        html : true,
        title: function() {  return $("#sessions-title").html(); },
        content: function() { $('#current_language_flag').popover('hide'); return $("#sessions-body").html(); }
    });
    $('#current_language_flag').popover({
        html : true,
        title: function() { return $("#languages-title").html(); },
        content: function() { $('#current_session_picture').popover('hide'); return $("#languages-body").html(); }
    });

i think there is a better way, maybe in mdm.js or bootstrab.min.js… this one works.

**Comment by xenopeek** [comment]
Thanks for contributing to MDM. We'll continue to fix MDM bugs but as the above doesn't break any functionality it is out of scope.
