### ISSUE TITLE
Show gecos instead of username

### ISSUE THREAD

**Issue by roman-yagodin** [linuxmint/mint-mdm-themes#26]
It may look like my personal opinion, but I really don't understand why default Mint-X HTML theme stick to showing username as primary label for the user. I think that using user gecos instead is better at least by two reasons:
1. It feels more secure when imaginary gecos displayed on screen than real login name.
2. User could easily change gecos, but changing username is not that simple.

So I suggest to switch to show gecos instead of username and fallback to username if there is no gecos for user. In this case there would be no need for secondary "name" label in the UI.

It could be even better to have some theme configuration options for this.

**Comment by JosephMcc** [comment]
We are no longer adding new features to MDM. Slick greeter plus LightDM are now the defaults in Linux Mint.
